#!/bin/bash
# Podcast für MP3-Player aufbereiten und löschen
# 2015-03-05 WB
# http://uafr.freeshell.org/schnitt/

##
## Defaulteinstellungen. Konfiguration hier anpassen.
##

# das Zielverzeichnis auf dem MP3-Player
PLAYER=/media/MP3_WB/Podcast
#PLAYER=/tmp/media

# Quelle nach Schnitt löschen (auch mit --keep/--del als erstem
# Parameter per Kommandozeile umschaltbar)
KEEP=false

# Schneiden erst wenn länger als $LENGTH Minuten
LENGTH=8

### Ende der Konfiguration ####

# Farben
    RED=`echo -e '\033[31m'`
  GREEN=`echo -e '\033[32m'`  
DYELLOW=`echo -e '\033[33m'`  
   BLUE=`echo -e '\033[34m'`  
  GBLUE=`echo -e '\033[35m'`
 NORMAL=`echo -e '\033[0m'`
 
  LGREY=`echo -e '\033[37m'`
  DGREY=`echo -e '\033[1;30m'`
##

ANSAGE=`mktemp --suffix=.wav`

# Kommandozeile auswerten 
if [ x"$1" = x"--keep" ] ; then
    KEEP=true
    shift
elif [ x"$1" = x"--del" ] ; then
    KEEP=false
    shift
fi

# Prüfen, ob Player gemountet ist
if [ ! -d "$PLAYER" ] ; then
    echo ${RED}ABBRUCH: Verzeichnis $PLAYER nicht gefunden.${NORMAL}
    exit -1
fi

# Info
if $KEEP ; then
    echo ${GREEN}Quelldateien nicht löschen.${NORMAL}
fi

# Dateien aufbereiten
for file in "$@" ; do
    if [ -r "$file" ] ; then
        name="`basename "$file" .mp3`"
        # genügend Platz vorhanden?
        KBISFREE=`df -k "$PLAYER" |grep / |awk '{print $4 }'`
        #Was brauchen wir? ca +100k für die Ansage
        let "FILESIZE = $(stat -c%s "$file") / 1024"
        let "FILESIZE += 100"

        folder="$PLAYER/${name// /_}"
        if [ $KBISFREE -lt $FILESIZE ] ; then
            echo ${RED}WARNUNG: Nicht genügend Platz für $file.${NORMAL}
        elif [ -e  "$folder" ] ; then
            echo ${RED}WARNUNG: Ordner $folder bereits vorhanden.${NORMAL}
        else
            mkdir "$folder"

            if [ ! -d "$folder" ] ; then
                echo ${RED}ABBRUCH: Verzeichnis $folder nicht angelegt.${NORMAL}
                exit -1
            fi

            # Ansage
            datum=`LC_TIME=de_DE.UTF8 date -r "$file" +"%A, %d. %B %Y"`
            name1=${name//_/ }
            title=`mid3v2 -l $file | grep -e TIT2 | cut -d= -f2-`
            minuten=`mp3info -p "%m" "$file"`
            dauer="Dauer etwa $minuten Minuten."
            echo ${name1//-/ } . vom $datum . $title . $dauer | \
             espeak --stdin -v german-mbrola-5  -s 100 -w $ANSAGE 2>>/dev/null
            lame --silent $ANSAGE "$folder/$name-000.mp3"

            if [[ $minuten -gt $LENGTH ]] ; then
                # Split und ggf. löschen
                mp3splt -1 -t 3.2 -o @f-@n -d "$folder" "$file" \
                 && ( if ! $KEEP ; then rm "$file" ; fi )
            else
                if $KEEP ; then
                    cp -v "$file" "$folder" 
                else
                    mv -v "$file" "$folder" 
                fi
            fi
        fi
    else
            echo ${RED}WARNUNG: $file nicht lesbar.${NORMAL}
    fi
done
rm $ANSAGE 

# freien Platz und verbleibende Dateien anzeigen
echo
df -h "$PLAYER"
ls -sh $* 2>/dev/null
